services:
  redis_service:
    image: redis:7-alpine
    container_name: redis_queue
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - whisperwave_network

  whisper_service:
    build: ./whisper_pipe
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis_service
    environment:
      - REDIS_URL=redis://redis_service:6379/0
      - LOG_PATH=/app/logs/transcriptions.jsonl
      - HF_HOME=/app/.models_cache
    volumes:
      - ./.logs/whisper_pipe:/app/logs
      - ./.models_cache:/app/.models_cache
    networks:
      - whisperwave_network

  classifier_service:
    build: ./classifier
    restart: always
    depends_on:
      - redis_service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_URL=redis://redis_service:6379/0
      - LOG_PATH=/app/logs/classifications.jsonl
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL_NAME=qwen3.5:9b-q4_K_M
    volumes:
      - ./.logs/classifier:/app/logs
    networks:
      - whisperwave_network

networks:
  whisperwave_network:
    driver: bridge

volumes:
  redis_data: